### ISSUE TITLE
Unexpected wording (typo?)

### ISSUE THREAD

**Issue by HelderMagalhaes** [Sir3eBpA/ffs#2]
In read me (highlight is mine):

> Add more file search options that support **Non-NFT** drives (obviously it won't be as fast as MFT

From context it appears that _Non-NFT_ should either be "Non-NTFS" or "Non-MFT". I'd prefer the latter, as it sounds more generic (multiple file systems implement MFT or a similar mechanism) but the former might be more accurate (given the dependency on the NTFS library). 😉

**Comment by Sir3eBpA** [comment]
Ah correct, nice catch!

**Comment by Sir3eBpA** [comment]
Fixed just now
